export {default as Home} from './Home.jsx'
export {default as Skills} from './Skills.jsx'
export {default as Projects} from './Projects.jsx'
export {default as Test} from './Test.jsx'
export {default as Contact} from './Contact.jsx'
export {default as Header} from './Header.jsx'
export {default as Dotbar} from './Dotbar.jsx'
export {default as Indicator} from './Indicator.jsx'
